version: "3.9"

services:
  api:
    build: ./
    image: url-shortener
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8080:8000"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
